name: real_workflow
on: push
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: echo "hello there"
  two:
    runs-on: ubuntu-latest
    steps:
      - name: question
        run: echo "are sure you understand"
